version: "3.3"

services:
  app:
    container_name: qwart-landing-page
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
